### ISSUE TITLE
报错了，大佬能帮忙看看吗

### ISSUE THREAD

**Issue by xovow** [hagerwang/png-mask-to-yolo-txt#1]
Traceback (most recent call last):
  File "D:/Desktop/paddlex/mask2txt_custom.py", line 71, in <module>
    mask_to_yolo("meter_seg/annotations/val_color", "meter_seg/annotations/val_txt", 2, 128, False)
  File "D:/Desktop/paddlex/mask2txt_custom.py", line 28, in mask_to_yolo
    w, h = img_current.shape
ValueError: too many values to unpack (expected 2)

**Comment by hagerwang** [comment]
> Traceback (most recent call last): File "D:/Desktop/paddlex/mask2txt_custom.py", line 71, in mask_to_yolo("meter_seg/annotations/val_color", "meter_seg/annotations/val_txt", 2, 128, False) File "D:/Desktop/paddlex/mask2txt_custom.py", line 28, in mask_to_yolo w, h = img_current.shape ValueError: too many values to unpack (expected 2)

掩码图片应该是个二维的  你的如果是三维的H,W,1的话把1那个维度squeeze了

**Comment by xovow** [comment]
> > Traceback (most recent call last): File "D:/Desktop/paddlex/mask2txt_custom.py", line 71, in mask_to_yolo("meter_seg/annotations/val_color", "meter_seg/annotations/val_txt", 2, 128, False) File "D:/Desktop/paddlex/mask2txt_custom.py", line 28, in mask_to_yolo w, h = img_current.shape ValueError: too many values to unpack (expected 2)
> 
> 掩码图片应该是个二维的 你的如果是三维的H,W,1的话把1那个维度squeeze了

我改成这个了`w, h, _ = img_current.shape`，但是又报另一个错了
```
Traceback (most recent call last):
  File "D:/Desktop/paddlex/mask2txt_custom.py", line 70, in <module>
    mask_to_yolo("meter_seg/annotations/train_color", "meter_seg/annotations/train_txt", 3, 128, False)
  File "D:/Desktop/paddlex/mask2txt_custom.py", line 34, in mask_to_yolo
    contours, _ = cv2.findContours(img_temp, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-6lylwdcz\opencv\modules\imgproc\src\contours.cpp:197: error: (-210:Unsupported format or combination of formats) [Start]FindContours supports only CV_8UC1 images when mode != CV_RETR_FLOODFILL otherwise supports CV_32SC1 images only in function 'cvStartFindContours_Impl'
```

**Comment by xovow** [comment]
另外我使用L模式的mask图转出来只有一个类别
```
0 0.335616 0.151163 0.33105 0.153488 0.326484 0.155814 0.33105 0.162791 0.3379 0.172093 0.340183 0.176744 0.33105 0.183721 0.335616 0.193023 0.3379 0.197674 0.340183 0.202326 0.342466 0.206977 0.344749 0.213953 0.347032 0.218605 0.351598 0.225581 0.353881 0.230233 0.356164 0.234884 0.360731 0.24186 0.363014 0.246512 0.36758 0.253488 0.369863 0.25814 0.372146 0.262791 0.374429 0.267442 0.376712 0.274419 0.378995 0.27907 0.383562 0.286047 0.385845 0.290698 0.388128 0.295349 0.392694 0.302326 0.394977 0.306977 0.399543 0.313953 0.401826 0.318605 0.40411 0.323256 0.406393 0.330233 0.408676 0.334884 0.410959 0.339535 0.413242 0.344186 0.417808 0.351163 0.420091 0.355814 0.424658 0.362791 0.426941 0.367442 0.429224 0.372093 0.43379 0.37907 0.436073 0.383721 0.438356 0.390698 0.440639 0.395349 0.442922 0.4 0.445205 0.404651 0.449772 0.411628 0.454338 0.418605 0.456621 0.423256 0.458904 0.427907 0.461187 0.432558 0.465753 0.439535 0.468037 0.444186 0.47032 0.451163 0.472603 0.455814 0.474886 0.460465 0.477169 0.465116 0.481735 0.472093 0.486301 0.47907 0.488584 0.483721 0.490868 0.488372 0.493151 0.493023 0.495434 0.497674 0.502283 0.493023 0.506849 0.490698 0.511416 0.488372 0.511416 0.486047 0.509132 0.481395 0.506849 0.476744 0.504566 0.469767 0.502283 0.465116 0.5 0.460465 0.495434 0.453488 0.493151 0.448837 0.488584 0.44186 0.486301 0.437209 0.484018 0.432558 0.479452 0.425581 0.477169 0.42093 0.474886 0.413953 0.472603 0.409302 0.47032 0.404651 0.468037 0.4 0.46347 0.393023 0.461187 0.388372 0.456621 0.381395 0.454338 0.376744 0.452055 0.372093 0.447489 0.365116 0.445205 0.360465 0.442922 0.353488 0.440639 0.348837 0.438356 0.344186 0.436073 0.339535 0.431507 0.332558 0.426941 0.325581 0.424658 0.32093 0.422374 0.316279 0.420091 0.311628 0.417808 0.306977 0.413242 0.3 0.410959 0.293023 0.408676 0.288372 0.406393 0.283721 0.40411 0.27907 0.401826 0.274419 0.394977 0.265116 0.392694 0.260465 0.390411 0.255814 0.388128 0.251163 0.385845 0.246512 0.381279 0.237209 0.378995 0.232558 0.376712 0.227907 0.374429 0.223256 0.372146 0.218605 0.369863 0.213953 0.363014 0.204651 0.360731 0.2 0.358447 0.195349 0.356164 0.190698 0.353881 0.186047 0.349315 0.176744 0.347032 0.172093 0.344749 0.167442 0.342466 0.162791 0.340183 0.15814
```
这是P模式mask图
![5](https://github.com/hagerwang/png-mask-to-yolo-txt/assets/78305714/46e48d08-6b49-47f7-80c9-eae92efcf3c7)
当validation=True时显示的图上只有指针
![image](https://github.com/hagerwang/png-mask-to-yolo-txt/assets/78305714/ebca7d44-960e-4820-a584-a5f6954d42c4)

**Comment by hagerwang** [comment]
> > > Traceback (most recent call last): File "D:/Desktop/paddlex/mask2txt_custom.py", line 71, in mask_to_yolo("meter_seg/annotations/val_color", "meter_seg/annotations/val_txt", 2, 128, False) File "D:/Desktop/paddlex/mask2txt_custom.py", line 28, in mask_to_yolo w, h = img_current.shape ValueError: too many values to unpack (expected 2)
> > 
> > 
> > 掩码图片应该是个二维的 你的如果是三维的H,W,1的话把1那个维度squeeze了
> 
> 我改成这个了`w, h, _ = img_current.shape`，但是又报另一个错了
> 
> ```
> Traceback (most recent call last):
>   File "D:/Desktop/paddlex/mask2txt_custom.py", line 70, in <module>
>     mask_to_yolo("meter_seg/annotations/train_color", "meter_seg/annotations/train_txt", 3, 128, False)
>   File "D:/Desktop/paddlex/mask2txt_custom.py", line 34, in mask_to_yolo
>     contours, _ = cv2.findContours(img_temp, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
> cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-6lylwdcz\opencv\modules\imgproc\src\contours.cpp:197: error: (-210:Unsupported format or combination of formats) [Start]FindContours supports only CV_8UC1 images when mode != CV_RETR_FLOODFILL otherwise supports CV_32SC1 images only in function 'cvStartFindContours_Impl'
> ```
我的代码只能处理H W二维的掩码 或者是H W 1转换成H W ，H W上要求每个像素的值就是对应的类别值 ，可视化验证是一个一个实例挨个显示的。你只是用_占了位但并没有对图片本身维度进行操作

**Comment by xovow** [comment]
可视化验证的那个我用的是二维的mask图
就这种![6](https://github.com/hagerwang/png-mask-to-yolo-txt/assets/78305714/520cc2b1-2384-45ac-b57e-0f019158951f)
